git subrepo commit lib/Marlin
subrepo:
  subdir:   "lib/Marlin"
  merged:   "eee71c95d1"
upstream:
  origin:   "git@github.com:prusa3d/Marlin.git"
  branch:   "buddy"
  commit:   "733ca940c0"
git-subrepo:
  version:  "0.4.3"
  origin:   "???"
  commit:   "???"

diff --git a/lib/Marlin/buildroot/bin/opt_disable b/lib/Marlin/buildroot/bin/opt_disable
--- a/lib/Marlin/buildroot/bin/opt_disable
+++ b/lib/Marlin/buildroot/bin/opt_disable
@@ -1,11 +1,15 @@
 #!/usr/bin/env bash
 
-SED=$(which gsed || which sed)
+# exit on first failure
+set -e
+
+SED=$(which gsed sed | head -n1)
 
 for opt in "$@" ; do
-  eval "${SED} -i 's/\([[:blank:]]*\)\(#define \b${opt}\b\)/\1\/\/\2/g' Marlin/Configuration.h"
-done
-
-for opt in "$@" ; do
-  eval "${SED} -i 's/\([[:blank:]]*\)\(#define \b${opt}\b\)/\1\/\/\2/g' Marlin/Configuration_adv.h"
+  DID=0 ; FOUND=0
+  for FN in Configuration Configuration_adv; do
+    "${SED}" -i "/^\(\s*\)\(#define\s\+${opt}\b\s\?\)\(\s\s\)\?/{s//\1\/\/\2/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
+    ((DID||FOUND)) || { grep -E "^\s*//\s*#define\s+${opt}\b" Marlin/$FN.h >/dev/null && FOUND=1 ; }
+  done
+  ((DID||FOUND)) || (echo "ERROR: $(basename $0) Can't find ${opt}" >&2 && exit 9)
 done
