git subrepo pull --force lib/Prusa-Error-Codes
subrepo:
  subdir:   "lib/Prusa-Error-Codes"
  merged:   "2a9961e71"
upstream:
  origin:   "git@github.com:prusa3d/Prusa-Error-Codes.git"
  branch:   "master"
  commit:   "2a9961e71"
git-subrepo:
  version:  "0.4.3"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "2f68596"

diff --git a/lib/Prusa-Error-Codes/.github/workflows/tests.yml b/lib/Prusa-Error-Codes/.github/workflows/tests.yml
--- a/lib/Prusa-Error-Codes/.github/workflows/tests.yml
+++ b/lib/Prusa-Error-Codes/.github/workflows/tests.yml
@@ -1,18 +1,24 @@
 name: Prusa error codes
 
-on: [push]
+on:
+  push:
+  pull_request:
 
 jobs:
   tests:
 
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        python-version: [ '3.10', '3.11', '3.12' ]
+
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v2
+    - uses: actions/checkout@v4
+    - name: Set up Python
+      uses: actions/setup-python@v5
       with:
-        python-version: 3.8
+        python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -21,10 +27,13 @@ jobs:
         pip install pyyaml
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint with pylint
+      id: pylint
       run: |
         python3 -m pylint --version
         python3 -m pylint --persistent=n --jobs 0 --max-line-length=120 prusaerrors
     - name: Test
+      # Run the step even if the pylint step has failed
+      if: success() || (failure() && steps.pylint.conclusion == 'failure')
       run: |
         export PATH="${PATH}:$(pwd)"
         coverage run -m unittest discover --failfast --verbose tests
